title: Maciej Szymkowski's Homepage
page-top-title: Maciej Szymkowski
top-section-bg-text: “AI is a mirror, reflecting not only our intellect, but our values and fears." – Ravi Narayanan
home-subtitle: Maciej Szymkowski
copyright-text: '&copy; Maciej Szymkowski 2023-2025. All Rights Reserved.'
