title: Maciej Szymkowski's Homepage
page-top-title: Maciej Szymkowski
top-section-bg-text: Computer Science
home-subtitle: Maciej Szymkowski
copyright-text: '&copy; Sen Li 2023-2024. All Rights Reserved.'
